### ISSUE TITLE
Enabling SDK Mode?

### ISSUE THREAD

**Issue by zemmyang** [Rexios80/polar#23]
I noticed when I tried to get the gyro stream settings (`polar.requestStreamSettings(identifier, PolarDataType.gyro);`) that the only available settings were 52Hz/2000dps. It looks like changing this is available by enabling SDK mode - does this package implement enabling it?

SDK mode ref: https://github.com/polarofficial/polar-ble-sdk/blob/master/documentation/SdkModeExplained.md

**Comment by Rexios80** [comment]
I tried to add this but am having this issue: https://github.com/polarofficial/polar-ble-sdk/issues/440

I think enabling SDK mode is working though so you can try this if you want
```yaml
polar:
  git:
    url: https://github.com/Rexios80/polar
    ref: 33638d4a43adcd1b488a028f38c85b9a357e145a
```
